@php
<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">';
echo '<title>index</title>';
echo '<link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Anton&amp;display=swap">';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&amp;display=swap">';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700&amp;display=swap">';
echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">';
echo '<link rel="stylesheet" href="assets/fonts/fontawesome-all.min.css">';
echo '<link rel="stylesheet" href="assets/fonts/font-awesome.min.css">';
echo '<link rel="stylesheet" href="assets/fonts/fontawesome5-overrides.min.css">';
echo '<link rel="stylesheet" href="assets/css/Animated-Pretty-Product-List-v12.css">';
echo '<link rel="stylesheet" href="assets/css/Black-Navbar.css">';
echo '<link rel="stylesheet" href="assets/css/canito-detalle-producto.css">';
echo '<link rel="stylesheet" href="assets/css/Data-Table-1.css">';
echo '<link rel="stylesheet" href="assets/css/Data-Table.css">';
echo '<link rel="stylesheet" href="assets/css/Drag--Drop-Upload-Form.css">';
echo '<link rel="stylesheet" href="assets/css/Features-Boxed.css">';
echo '<link rel="stylesheet" href="assets/css/Footer-Basic.css">';
echo '<link rel="stylesheet" href="assets/css/Form-Search.css">';
echo '<link rel="stylesheet" href="assets/css/Header-Blue.css">';
echo '<link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">';
echo '<link rel="stylesheet" href="assets/css/Pretty-Registration-Form.css">';
echo '<link rel="stylesheet" href="assets/css/Registration-Form-with-Photo.css">';
echo '<link rel="stylesheet" href="assets/css/Reviews.css">';
echo '<link rel="stylesheet" href="assets/css/Sidebar-Cool-SB-Admin-Inspirate.css">';
echo '<link rel="stylesheet" href="assets/css/styles.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<header class="header-blue">';
echo '<nav class="navbar navbar-dark navbar-expand-md navigation-clean-search">';
echo '<div class="container-fluid"><a class="navbar-brand" href="index.html">Meet My Books</a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>';
echo '<div class="collapse navbar-collapse" id="navcol-1">';
echo '<ul class="navbar-nav">';
echo '<li class="nav-item"></li>';
echo '</ul>';
echo '<form class="d-flex me-auto navbar-form" target="_self">';
echo '<div class="d-flex align-items-center"><label class="form-label d-flex mb-0" for="search-field"></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>';
echo '</form><span class="navbar-text"> </span>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '<div class="container hero"><form method="post">';
echo '<h2 class="text-center text-light"><strong>Iniciar sesión</strong></h2>';
echo '<div class="mb-3"><input type="email" class="form-control" name="email" placeholder="Correo electrónico" /></div>';
echo '<div class="mb-3"><input type="password" class="form-control" name="password" placeholder="Contraseña" /></div>';
echo '<div class="mb-3"></div>';
echo '<div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit">Iniciar sesión</button></div><a class="already" href="registro.html">¿No tienes una cuenta? Regístrate</a>';
echo '</form></div>';
echo '</header>';
echo '<script src="assets/bootstrap/js/bootstrap.min.js"></script>';
echo '<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>';
echo '<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>';
echo '<script src="assets/js/Animated-Pretty-Product-List-v12.js"></script>';
echo '</body>';
echo '';
echo '</html>';
?>
@endphp
